version: '3.9'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: on-failure
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
            - .:/app
        networks:
            - node-server
        depends_on:
            - mongo
            - redis
        env_file:
            - .env
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - data:/data/db
        networks:
            - node-server
    redis:
        image: redis
        networks:
            - node-server
        ports:
            - 6379:6379
        volumes:
            - myredis:/usr/local/etc/redis
networks:
    node-server:
volumes:
    data:
    myredis:
