version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - node-server
    links:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - node-server
networks:
  node-server:
volumes:
 data: