version: '3.9'

services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: on-failure
        ports:
            - ${PORT}:${NODE_DOCKER_PORT}
        volumes:
            - /app/node_modules
            - .:/app
        networks:
            - node-server
        depends_on:
            - mongodb
        env_file:
            - .env
    mongodb:
        image: mongo
        container_name: mongodb
        restart: unless-stopped
        ports:
            - ${MONGODB_PORT}:${MONGODB_DOCKER_PORT}
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
        volumes:
            - data:/data/db
        networks:
            - node-server
networks:
    node-server:
volumes:
    data:
