auth_enabled: false

server:
    http_listen_port: 3100

ingester:
    lifecycler:
        address: loki:3100
        ring:
            kvstore:
                store: inmemory

schema_config:
    configs:
        - from: 2020-04-15
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
              prefix: index_
              period: 24h

storage_config:
    boltdb:
        directory: /tmp/loki/index

limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h

chunk_store_config:
    max_look_back_period: 0s

table_manager:
    retention_deletes_enabled: true
    retention_period: 30d
