name: Run Tests

on:
    pull_request:
        branches:
            - main
            - staging
    push:
        branches:
            - main
permissions: read-all
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Build Docker image
              run: docker build -t my-node-app-test -f Dockerfile.dev .

            - name: Run Docker container for tests
              run: docker run my-node-app-test
