name: Run Tests

on:
    pull_request:
        branches:
            - main
            - staging
    push:
        branches:
            - main
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: --name mongodb

    env:
      MONGODB_URL: mongodb://localhost:27017/mydatabase
      ACCESS_TOKEN_SECRET: aa6db53b9d83fb0fc5b960ee33a10f5fec3670cc92f616649fe2279051f37ca0e73a9778fc9d1421150ea2db7bea6a1dfeaf57883473bad87212c504409d5cd7
      REFRESH_TOKEN_SECRET: c8448c09acb0b824541d45eb0820a6912cd20d23f06a3f49ef49cb606674dbc4e572de6a1b78bb896032b5c2bfff488dc328774b07ec0b1ef2bce0183e3c3e25

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test